"""Initial migration with start_timestamp and end_timestamp

Revision ID: 70714f97242d
Revises: 
Create Date: 2024-08-19 17:23:36.925762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70714f97242d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.String(length=16), nullable=False),
    sa.Column('group', sa.String(length=50), nullable=False),
    sa.Column('session_num', sa.Integer(), nullable=False),
    sa.Column('round_num', sa.Integer(), nullable=False),
    sa.Column('contribution', sa.Integer(), nullable=False),
    sa.Column('bot_contribution', sa.Integer(), nullable=False),
    sa.Column('participant_balance', sa.Integer(), nullable=False),
    sa.Column('bot_balance', sa.Integer(), nullable=False),
    sa.Column('net_gain', sa.Integer(), nullable=False),
    sa.Column('time_exceeded', sa.Integer(), nullable=False),
    sa.Column('start_timestamp', sa.DateTime(), nullable=True),
    sa.Column('end_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_id', 'session_num', 'round_num', name='_participant_session_round_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant')
    # ### end Alembic commands ###
