"""Add bonus column to Participant table

Revision ID: bc2ad633b940
Revises: f420ef02c2ba
Create Date: 2024-09-19 09:38:09.055690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc2ad633b940'
down_revision = 'f420ef02c2ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_column('bonus')

    # ### end Alembic commands ###
