"""Reinitializing migrations

Revision ID: ce601f0e5319
Revises: 
Create Date: 2024-09-17 02:24:42.461840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce601f0e5319'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('belief_1_1', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('belief_1_10', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('belief_2_1', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('belief_2_10', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('incom_1', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('incom_2', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('incom_3', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('incom_4', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('incom_5', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('incom_6', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('earnings', sa.Float(), nullable=False))
        batch_op.alter_column('participant_balance',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('bot_balance',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('net_gain',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_column('time_exceeded')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_exceeded', sa.INTEGER(), nullable=False))
        batch_op.alter_column('net_gain',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('bot_balance',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('participant_balance',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('earnings')
        batch_op.drop_column('incom_6')
        batch_op.drop_column('incom_5')
        batch_op.drop_column('incom_4')
        batch_op.drop_column('incom_3')
        batch_op.drop_column('incom_2')
        batch_op.drop_column('incom_1')
        batch_op.drop_column('belief_2_10')
        batch_op.drop_column('belief_2_1')
        batch_op.drop_column('belief_1_10')
        batch_op.drop_column('belief_1_1')

    # ### end Alembic commands ###
