"""Add start_timestamp and end_timestamp to Participant model

Revision ID: d622c362adc7
Revises: 
Create Date: 2024-08-19 16:50:38.938691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd622c362adc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('start_timestamp', sa.DateTime(), nullable=True))
    op.add_column('participant', sa.Column('end_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participant')
    # ### end Alembic commands ###
