"""Add Prolific PID and session ID to Participant

Revision ID: f420ef02c2ba
Revises: ce601f0e5319
Create Date: 2024-09-18 21:35:13.709427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f420ef02c2ba'
down_revision = 'ce601f0e5319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prolific_pid', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('session_id', sa.String(length=64), nullable=False))
        batch_op.drop_column('belief_1_1')
        batch_op.drop_column('earnings')
        batch_op.drop_column('belief_1_10')
        batch_op.drop_column('belief_2_1')
        batch_op.drop_column('belief_2_10')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('belief_2_10', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('belief_2_1', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('belief_1_10', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('earnings', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('belief_1_1', sa.INTEGER(), nullable=False))
        batch_op.drop_column('session_id')
        batch_op.drop_column('prolific_pid')

    # ### end Alembic commands ###
